const countryList = {
  "United Arab Emirates": "AED",
  "Afghanistan": "AFN",
  "Antigua and Barbuda": "XCD",
  "Albania": "ALL",
  "Armenia": "AMD",
  "Netherlands Antilles": "ANG",
  "Angola": "AOA",
  "Antarctica": "AQD",
  "Argentina": "ARS",
  "Australia": "AUD",
  "Azerbaijan": "AZN",
  "Bosnia and Herzegovina": "BAM",
  "Barbados": "BBD",
  "Bangladesh": "BDT",
  "Benin": "XOF",
  "Bulgaria": "BGN",
  "Bahrain": "BHD",
  "Burundi": "BIF",
  "Bermuda": "BMD",
  "Brunei": "BND",
  "Bolivia": "BOB",
  "Brazil": "BRL",
  "Bahamas": "BSD",
  "Bouvet Island": "NOK",
  "Botswana": "BWP",
  "Belarus": "BYR",
  "Belize": "BZD",
  "Canada": "CAD",
  "Congo - Kinshasa": "CDF",
  "Central African Republic": "XAF",
  "Switzerland": "CHF",
  "Chile": "CLP",
  "China": "CNY",
  "Colombia": "COP",
  "Costa Rica": "CRC",
  "Cuba": "CUP",
  "Cape Verde": "CVE",
  "Cyprus": "CYP",
  "Czech Republic": "CZK",
  "Djibouti": "DJF",
  "Denmark": "DKK",
  "Dominican Republic": "DOP",
  "Algeria": "DZD",
  "Ecuador": "ECS",
  "Estonia": "EEK",
  "Egypt": "EGP",
  "Ethiopia": "ETB",
  "France": "EUR",
  "Fiji": "FJD",
  "Falkland Islands": "FKP",
  "United Kingdom": "GBP",
  "Georgia": "GEL",
  "Guernsey": "GGP",
  "Ghana": "GHS",
  "Gibraltar": "GIP",
  "Gambia": "GMD",
  "Guinea": "GNF",
  "Guatemala": "GTQ",
  "Guyana": "GYD",
  "Hong Kong": "HKD",
  "Honduras": "HNL",
  "Croatia": "HRK",
  "Haiti": "HTG",
  "Hungary": "HUF",
  "Indonesia": "IDR",
  "Israel": "ILS",
  "India": "INR",
  "Iraq": "IQD",
  "Iran": "IRR",
  "Iceland": "ISK",
  "Jamaica": "JMD",
  "Jordan": "JOD",
  "Japan": "JPY",
  "Kenya": "KES",
  "Kyrgyzstan": "KGS",
  "Cambodia": "KHR",
  "Comoros": "KMF",
  "North Korea": "KPW",
  "South Korea": "KRW",
  "Kuwait": "KWD",
  "Cayman Islands": "KYD",
  "Kazakhstan": "KZT",
  "Laos": "LAK",
  "Lebanon": "LBP",
  "Sri Lanka": "LKR",
  "Liberia": "LRD",
  "Lesotho": "LSL",
  "Lithuania": "LTL",
  "Latvia": "LVL",
  "Libya": "LYD",
  "Morocco": "MAD",
  "Moldova": "MDL",
  "Madagascar": "MGA",
  "Macedonia": "MKD",
  "Myanmar (Burma)": "MMK",
  "Mongolia": "MNT",
  "Macau": "MOP",
  "Mauritania": "MRO",
  "Malta": "MTL",
  "Mauritius": "MUR",
  "Maldives": "MVR",
  "Malawi": "MWK",
  "Mexico": "MXN",
  "Malaysia": "MYR",
  "Mozambique": "MZN",
  "Namibia": "NAD",
  "New Caledonia": "XPF",
  "Nigeria": "NGN",
  "Nicaragua": "NIO",
  "Nepal": "NPR",
  "New Zealand": "NZD",
  "Oman": "OMR",
  "Panama": "PAB",
  "Peru": "PEN",
  "Papua New Guinea": "PGK",
  "Philippines": "PHP",
  "Pakistan": "PKR",
  "Poland": "PLN",
  "Paraguay": "PYG",
  "Qatar": "QAR",
  "Romania": "RON",
  "Serbia": "RSD",
  "Russia": "RUB",
  "Rwanda": "RWF",
  "Saudi Arabia": "SAR",
  "Solomon Islands": "SBD",
  "Seychelles": "SCR",
  "Sudan": "SDG",
  "Sweden": "SEK",
  "Singapore": "SGD",
  "Slovakia": "SKK",
  "Sierra Leone": "SLL",
  "Somalia": "SOS",
  "Suriname": "SRD",
  "São Tomé and Príncipe": "STD",
  "El Salvador": "SVC",
  "Syria": "SYP",
  "Eswatini": "SZL",
  "Thailand": "THB",
  "Tajikistan": "TJS",
  "Turkmenistan": "TMT",
  "Tunisia": "TND",
  "Tonga": "TOP",
  "Turkey": "TRY",
  "Trinidad and Tobago": "TTD",
  "Taiwan": "TWD",
  "Tanzania": "TZS",
  "Ukraine": "UAH",
  "Uganda": "UGX",
  "United States": "USD",
  "Uruguay": "UYU",
  "Uzbekistan": "UZS",
  "Venezuela": "VEF",
  "Vietnam": "VND",
  "Vanuatu": "VUV",
  "Yemen": "YER",
  "South Africa": "ZAR",
  "Zambia": "ZMK",
  "Zimbabwe": "ZWD"
};
